blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/urls.py
from django.urls import path

from contact import views
app_name = 'contact'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    #contatos (CRUD)
    path('contact/<int:contact_id>/detail', views.contact, name='contact'),    
    path('contact/create/', views.create, name='create'),    
    path('contact/<int:contact_id>/update/', views.update, name='update'),    
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),    
]

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    
    class Meta:
        verbose_name: "Category"
        verbose_name_plural: 'Categories'
        
    name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return self.name
    

class Contact(models.Model): 
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    created_date = models.DateField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%M')
    category = models.ForeignKey(Category, 
                                 on_delete=models.SET_NULL, blank=True, 
                                 null=True)
    
    owner = models.ForeignKey(User, 
                                 on_delete=models.SET_NULL, blank=True, 
                                 null=True)
    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name} {self.email}'
    

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError

from . import models

class ContactForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'classe-a classe-b',
                'placeholder': 'digite seu texto aqui',
            }
        ),
        label='Primeiro nome',
        help_text="texto de ajuda"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)

        # self.fields['first_name'].widget.attrs.update({
        #     'class':'classe-a classe-b',
        #     'placeholder':'digite aqui :)',   
        # })

    class Meta:
        model = models.Contact
        fields = ( 'first_name', 
        'last_name',
        'phone', 'email', 'description', 'category',
        ) 

        
        # widgets = { 
        #     'first_name': forms.TextInput(
        #         attrs={
        #             'class':'classe-a classe-b',
        #             'placeholder':'digite seu nome aqui :)' 
        #         }
        #     )
        # }

    def clean(self):

        cleaned_data = self.cleaned_data

        self.add_error(
            None,
            ValidationError(
                'Deu erro, amigo.',
                code='invalid',

            )
        )
        return super().clean()

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        
        
        if first_name == 'ABC':
          self.add_error(
            'first_name',ValidationError(
                "veio do add_error",
                code='invalid'
            )
          )
        return first_name
    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
    
        return last_name
    def clean(self):

        cleaned_data = super().clean()

        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name and last_name and first_name == last_name:
            self.add_error(
                'last_name', ValidationError(
                    "last name não pode ser igual ao first_name", code= 'invalid'
                )
            )

contact/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(
        request,
        'contact/index.html',
    )

contact/views/contact_forms.py
from django.shortcuts import get_object_or_404, render, redirect
from contact.models import Contact
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator
from django.urls import reverse

from contact.forms import ContactForm

def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST)
        context = {
            'form':form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)
    
            
        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(),
        'form_action': form_action,
        'page_title': 'Criar Contato vindo page_title'
    }
    

    return render(
        request,
        'contact/create.html',
        context
    )

def update(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id,show=True
        )
    form_action = reverse('contact:update', args=(contact_id,))
    

    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)

        context = {
            'form':form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save(commit=False)
            contact.save()
            return redirect('contact:update',contact_id=contact.pk)
    
            
        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(),
        'form_action': form_action,
        'page_title': "Atualizar Contato",
    }
    

    return render(
        request,
        'contact/create.html',
        context
    )

def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )

    confirmation = request.POST.get('confirmation', 'no')
    print('confirmation', confirmation)

    if confirmation == 'sim':
        contact.delete()
        return redirect('contact:index')
    


    # contact.delete()
    # return redirect('contact:index')

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation
        }
    )

contact/views/contact_views.py
from django.shortcuts import get_object_or_404, render, redirect
from contact.models import Contact
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator



# Create your views here.

def index(request):
    contacts = Contact.objects \
    .filter(show=True) \
    .order_by('-id')

    paginator = Paginator(contacts,10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos -'
    }
    return render(
        request,
        'contact/index.html',
        context
    )
    
def search(request):
    search_value = request.GET.get('q', '').strip()
    
    if search_value == '':
        return redirect('contact:index')
    
    contacts = Contact.objects \
    .filter(show=True) \
    .filter(
        Q(first_name__icontains=search_value) |
        Q(last_name__icontains=search_value) |
        Q(phone__icontains=search_value) |
        Q(email__icontains=search_value) 
    )\
    .order_by('-id')
    
    paginator = Paginator(contacts,10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj':page_obj,
        'site_title': 'Pesquisa -',
        'search_value': search_value,
    }
    return render(
        request,
        'contact/index.html',
        context
    )

def contact(request, contact_id):
    #single_contact = Contact.objects.filter(pk=contact_id).first()
    try:
        single_contact = get_object_or_404(Contact,pk=contact_id, show=True)
    except Contact.DoesNotExist:
        return redirect('index')
    
    site_title = f'{single_contact.first_name} { single_contact.last_name } -'
    
    context = {
        'contact':single_contact,
        'site_title': site_title
    }
    return render(
        request,
        'contact/contact.html',
        context
    )

contact/templates/contact/contact.html
{% extends 'global/base.html' %}


{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
        {{contact.first_name}} {{contact.last_name}}
        </h1>
        <p><b>ID:</b> {{contact.id}}</p>
        <p><b>Email:</b> {{contact.email}}</p>
        <p><b>Data de Criação:</b> {{contact.created_date}}</p>
        <p><b>Descrição:</b> {{contact.description}}</p>
        <p><b>Categoria:</b> {{contact.category.name}}</p>

        <div class="contact-links">
            <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Atualizar</a>

            <form action="{% url 'contact:delete' contact.id %}" method="POST">
                {% csrf_token %}

                {% if confirmation == 'no' %}
                    <input type="hidden" name="confirmation" value="sim" />
                    <button class="btn btn-link btn-delete" type="submit">Confirmar?</button>
                {% else %}
                   <button class="btn btn-link btn-delete" type="submit">Apagar</button>
                {% endif %}
            
            </form>
        </div>

    </div>
    

{% endblock content %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
<div class="form-wrapper">
    <h2>{{ page_title }}</h2>
    <form action="{{ form_action }}"
        method='POST'
        enctype="multi/from-data"
    >
    {% csrf_token %}

    {% for field in form %}
    <div class="form-content">
        <div class="form-group">
            <label for="{{field.id_for_label}}"> {{field.label}} </label>
            {{ field }}
            {{ field.errors }}
            {% if field.help_text %}
                <p class="help-text">
                    {{ field.help_text }}
                </p>
            {% endif %}
        </div>
        {% endfor %}    
    </div>
    
    {% if form.non_field_errors %}
        <div class="form-content">
            <div class="form-group">
                <div class="message error">
            {{form.non_field_errors}}
            </div>
        </div>
    {% endif %}


    <div class="class form-content">
        <div class="class form-group">
            <button class="class btn" type="send"> Enviar </button>
        </div>
    </div>

</div>
</form>

{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
{% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Contatos
                <div class="reponsive-table">
                <a class="table-link" href="{% url 'contact:create' %}"> Criar Contato</a>
                </div>
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID </th>
                    <th class="table-header">Nome </th>
                    <th class="table-header">Sobrenome </th>
                    <th class="table-header">Telefone </th>
                    <th class="table-header">E-mail </th>
                    <th class="table-header">check </th>
                
                </tr>
            </thead>

            <tbody>
                {% for contact in page_obj %}
                <tr class="table-row">
                    <td class="table-cel">
                        <a class="table-link" href="{% url 'contact:contact' contact.id %}" >
                        {{contact.id}}
                        </a>
                    </td>

                    <td class="table-cel">
                        {{contact.first_name}}

                    </td>
                    
                    <td class="table-cel"> 
                        {{contact.last_name}}

                    </td>
                    <td class="table-cel">
                        {{contact.phone}}

                    </td>

                    <td class="table-cel">
                        {{contact.email}}

                    </td>
                    <td class="table-cel">
                        {{contact.show}}

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
{% include 'contact/404.html' %}
{% endif %}
{% endblock content %}